language: python
python:
  - "3.9"

before_install:
  - cd PyDa/discord

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - echo $WEBHOOK_URL

script:
  - pytest
  - sonar-scanner

after_script:
  - docker build -t phillip .
  - docker tag phillip:latest skylervermeer/phillip:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push skylervermeer/phillip:latest


after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

services:
  - docker

addons:
  sonarcloud:
    organization: "s-vermeer"
    token: $SONAR_TOKEN