language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_install:
  - cd PyDa/discord
script:
  - pytest

after_success:
  - cd ../
  - docker build -t phillip .
  - docker tag phillip:latest skylervermeer/phillip:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push skylervermeer/phillip:latest
  - curl -X POST http://31.187.231.118:9000/api/webhooks/ae98d030-0736-4227-9ac8-c31a948a0109
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

services:
  - docker

addons:
  sonarcloud:
    token:
      secure: "783e4cc34e0aaa10abaf4e19821833752c4f2d44"